// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzkqsdyijmsajjlaoqwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6a3FzZHlpam1zYWpqbGFvcXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzk0MDcsImV4cCI6MjA2MjkxNTQwN30.H-4OK8vTBGpQGPKuYqAHvWwXaRVMnwuOj69cx4MyG98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);